### ISSUE TITLE
想知道支不支持manylinux的whl

### ISSUE THREAD

**Issue by cibimo** [hzyitc/armbian-onecloud#200]
能有人帮忙发下
`python -m pip debug --verbose`
的输出么，想知道支不支持manylinux的whl

**Comment by CatGuai** [comment]
root@onecloud ~# python3 -m pip debug --verbose
WARNING: This command is only meant for debugging. Do not use this with automation for parsing and getting these details, since the output and options of this command may change without notice.
pip version: pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)
sys.version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
sys.executable: /usr/bin/python3
sys.getdefaultencoding: utf-8
sys.getfilesystemencoding: utf-8
locale.getpreferredencoding: UTF-8
sys.platform: linux
sys.implementation:
  name: cpython
'cert' config value: Not specified
REQUESTS_CA_BUNDLE: None
CURL_CA_BUNDLE: None
pip._vendor.certifi.where(): /etc/ssl/certs/ca-certificates.crt
pip._vendor.DEBUNDLED: False
vendored library versions:
  CacheControl==0.12.10
  colorama==0.4.4
  distlib==0.3.4
  distro==1.6.0
  html5lib==1.1
  msgpack==1.0.3 (Unable to locate actual module version, using vendor.txt specified version)
  packaging==21.3
  pep517==0.12.0
  platformdirs==2.4.1
  progress==1.6
  pyparsing==3.0.7
  requests==2.27.1
  certifi==2021.10.08
  chardet==4.0.0
  idna==3.3
  urllib3==1.26.8
  rich==11.0.0 (Unable to locate actual module version, using vendor.txt specified version)
  pygments==2.11.2
  typing_extensions==4.0.1 (Unable to locate actual module version, using vendor.txt specified version)
  resolvelib==0.8.1
  setuptools==44.0.0 (Unable to locate actual module version, using vendor.txt specified version)
  six==1.16.0
  tenacity==8.0.1 (Unable to locate actual module version, using vendor.txt specified version)
  tomli==1.0.3
  webencodings==0.5.1 (Unable to locate actual module version, using vendor.txt specified version)
Compatible tags: 496
  cp310-cp310-manylinux_2_35_armv7l
  cp310-cp310-manylinux_2_34_armv7l
  cp310-cp310-manylinux_2_33_armv7l
  cp310-cp310-manylinux_2_32_armv7l
  cp310-cp310-manylinux_2_31_armv7l
  cp310-cp310-manylinux_2_30_armv7l
  cp310-cp310-manylinux_2_29_armv7l
  cp310-cp310-manylinux_2_28_armv7l
  cp310-cp310-manylinux_2_27_armv7l
  cp310-cp310-manylinux_2_26_armv7l
  cp310-cp310-manylinux_2_25_armv7l
  cp310-cp310-manylinux_2_24_armv7l
  cp310-cp310-manylinux_2_23_armv7l
  cp310-cp310-manylinux_2_22_armv7l
  cp310-cp310-manylinux_2_21_armv7l
  cp310-cp310-manylinux_2_20_armv7l
  cp310-cp310-manylinux_2_19_armv7l
  cp310-cp310-manylinux_2_18_armv7l
  cp310-cp310-manylinux_2_17_armv7l
  cp310-cp310-manylinux2014_armv7l
  cp310-cp310-linux_armv7l
  cp310-abi3-manylinux_2_35_armv7l
  cp310-abi3-manylinux_2_34_armv7l
  cp310-abi3-manylinux_2_33_armv7l
  cp310-abi3-manylinux_2_32_armv7l
  cp310-abi3-manylinux_2_31_armv7l
  cp310-abi3-manylinux_2_30_armv7l
  cp310-abi3-manylinux_2_29_armv7l
  cp310-abi3-manylinux_2_28_armv7l
  cp310-abi3-manylinux_2_27_armv7l
  cp310-abi3-manylinux_2_26_armv7l
  cp310-abi3-manylinux_2_25_armv7l
  cp310-abi3-manylinux_2_24_armv7l
  cp310-abi3-manylinux_2_23_armv7l
  cp310-abi3-manylinux_2_22_armv7l
  cp310-abi3-manylinux_2_21_armv7l
  cp310-abi3-manylinux_2_20_armv7l
  cp310-abi3-manylinux_2_19_armv7l
  cp310-abi3-manylinux_2_18_armv7l
  cp310-abi3-manylinux_2_17_armv7l
  cp310-abi3-manylinux2014_armv7l
  cp310-abi3-linux_armv7l
  cp310-none-manylinux_2_35_armv7l
  cp310-none-manylinux_2_34_armv7l
  cp310-none-manylinux_2_33_armv7l
  cp310-none-manylinux_2_32_armv7l
  cp310-none-manylinux_2_31_armv7l
  cp310-none-manylinux_2_30_armv7l
  cp310-none-manylinux_2_29_armv7l
  cp310-none-manylinux_2_28_armv7l
  cp310-none-manylinux_2_27_armv7l
  cp310-none-manylinux_2_26_armv7l
  cp310-none-manylinux_2_25_armv7l
  cp310-none-manylinux_2_24_armv7l
  cp310-none-manylinux_2_23_armv7l
  cp310-none-manylinux_2_22_armv7l
  cp310-none-manylinux_2_21_armv7l
  cp310-none-manylinux_2_20_armv7l
  cp310-none-manylinux_2_19_armv7l
  cp310-none-manylinux_2_18_armv7l
  cp310-none-manylinux_2_17_armv7l
  cp310-none-manylinux2014_armv7l
  cp310-none-linux_armv7l
  cp39-abi3-manylinux_2_35_armv7l
  cp39-abi3-manylinux_2_34_armv7l
  cp39-abi3-manylinux_2_33_armv7l
  cp39-abi3-manylinux_2_32_armv7l
  cp39-abi3-manylinux_2_31_armv7l
  cp39-abi3-manylinux_2_30_armv7l
  cp39-abi3-manylinux_2_29_armv7l
  cp39-abi3-manylinux_2_28_armv7l
  cp39-abi3-manylinux_2_27_armv7l
  cp39-abi3-manylinux_2_26_armv7l
  cp39-abi3-manylinux_2_25_armv7l
  cp39-abi3-manylinux_2_24_armv7l
  cp39-abi3-manylinux_2_23_armv7l
  cp39-abi3-manylinux_2_22_armv7l
  cp39-abi3-manylinux_2_21_armv7l
  cp39-abi3-manylinux_2_20_armv7l
  cp39-abi3-manylinux_2_19_armv7l
  cp39-abi3-manylinux_2_18_armv7l
  cp39-abi3-manylinux_2_17_armv7l
  cp39-abi3-manylinux2014_armv7l
  cp39-abi3-linux_armv7l
  cp38-abi3-manylinux_2_35_armv7l
  cp38-abi3-manylinux_2_34_armv7l
  cp38-abi3-manylinux_2_33_armv7l
  cp38-abi3-manylinux_2_32_armv7l
  cp38-abi3-manylinux_2_31_armv7l
  cp38-abi3-manylinux_2_30_armv7l
  cp38-abi3-manylinux_2_29_armv7l
  cp38-abi3-manylinux_2_28_armv7l
  cp38-abi3-manylinux_2_27_armv7l
  cp38-abi3-manylinux_2_26_armv7l
  cp38-abi3-manylinux_2_25_armv7l
  cp38-abi3-manylinux_2_24_armv7l
  cp38-abi3-manylinux_2_23_armv7l
  cp38-abi3-manylinux_2_22_armv7l
  cp38-abi3-manylinux_2_21_armv7l
  cp38-abi3-manylinux_2_20_armv7l
  cp38-abi3-manylinux_2_19_armv7l
  cp38-abi3-manylinux_2_18_armv7l
  cp38-abi3-manylinux_2_17_armv7l
  cp38-abi3-manylinux2014_armv7l
  cp38-abi3-linux_armv7l
  cp37-abi3-manylinux_2_35_armv7l
  cp37-abi3-manylinux_2_34_armv7l
  cp37-abi3-manylinux_2_33_armv7l
  cp37-abi3-manylinux_2_32_armv7l
  cp37-abi3-manylinux_2_31_armv7l
  cp37-abi3-manylinux_2_30_armv7l
  cp37-abi3-manylinux_2_29_armv7l
  cp37-abi3-manylinux_2_28_armv7l
  cp37-abi3-manylinux_2_27_armv7l
  cp37-abi3-manylinux_2_26_armv7l
  cp37-abi3-manylinux_2_25_armv7l
  cp37-abi3-manylinux_2_24_armv7l
  cp37-abi3-manylinux_2_23_armv7l
  cp37-abi3-manylinux_2_22_armv7l
  cp37-abi3-manylinux_2_21_armv7l
  cp37-abi3-manylinux_2_20_armv7l
  cp37-abi3-manylinux_2_19_armv7l
  cp37-abi3-manylinux_2_18_armv7l
  cp37-abi3-manylinux_2_17_armv7l
  cp37-abi3-manylinux2014_armv7l
  cp37-abi3-linux_armv7l
  cp36-abi3-manylinux_2_35_armv7l
  cp36-abi3-manylinux_2_34_armv7l
  cp36-abi3-manylinux_2_33_armv7l
  cp36-abi3-manylinux_2_32_armv7l
  cp36-abi3-manylinux_2_31_armv7l
  cp36-abi3-manylinux_2_30_armv7l
  cp36-abi3-manylinux_2_29_armv7l
  cp36-abi3-manylinux_2_28_armv7l
  cp36-abi3-manylinux_2_27_armv7l
  cp36-abi3-manylinux_2_26_armv7l
  cp36-abi3-manylinux_2_25_armv7l
  cp36-abi3-manylinux_2_24_armv7l
  cp36-abi3-manylinux_2_23_armv7l
  cp36-abi3-manylinux_2_22_armv7l
  cp36-abi3-manylinux_2_21_armv7l
  cp36-abi3-manylinux_2_20_armv7l
  cp36-abi3-manylinux_2_19_armv7l
  cp36-abi3-manylinux_2_18_armv7l
  cp36-abi3-manylinux_2_17_armv7l
  cp36-abi3-manylinux2014_armv7l
  cp36-abi3-linux_armv7l
  cp35-abi3-manylinux_2_35_armv7l
  cp35-abi3-manylinux_2_34_armv7l
  cp35-abi3-manylinux_2_33_armv7l
  cp35-abi3-manylinux_2_32_armv7l
  cp35-abi3-manylinux_2_31_armv7l
  cp35-abi3-manylinux_2_30_armv7l
  cp35-abi3-manylinux_2_29_armv7l
  cp35-abi3-manylinux_2_28_armv7l
  cp35-abi3-manylinux_2_27_armv7l
  cp35-abi3-manylinux_2_26_armv7l
  cp35-abi3-manylinux_2_25_armv7l
  cp35-abi3-manylinux_2_24_armv7l
  cp35-abi3-manylinux_2_23_armv7l
  cp35-abi3-manylinux_2_22_armv7l
  cp35-abi3-manylinux_2_21_armv7l
  cp35-abi3-manylinux_2_20_armv7l
  cp35-abi3-manylinux_2_19_armv7l
  cp35-abi3-manylinux_2_18_armv7l
  cp35-abi3-manylinux_2_17_armv7l
  cp35-abi3-manylinux2014_armv7l
  cp35-abi3-linux_armv7l
  cp34-abi3-manylinux_2_35_armv7l
  cp34-abi3-manylinux_2_34_armv7l
  cp34-abi3-manylinux_2_33_armv7l
  cp34-abi3-manylinux_2_32_armv7l
  cp34-abi3-manylinux_2_31_armv7l
  cp34-abi3-manylinux_2_30_armv7l
  cp34-abi3-manylinux_2_29_armv7l
  cp34-abi3-manylinux_2_28_armv7l
  cp34-abi3-manylinux_2_27_armv7l
  cp34-abi3-manylinux_2_26_armv7l
  cp34-abi3-manylinux_2_25_armv7l
  cp34-abi3-manylinux_2_24_armv7l
  cp34-abi3-manylinux_2_23_armv7l
  cp34-abi3-manylinux_2_22_armv7l
  cp34-abi3-manylinux_2_21_armv7l
  cp34-abi3-manylinux_2_20_armv7l
  cp34-abi3-manylinux_2_19_armv7l
  cp34-abi3-manylinux_2_18_armv7l
  cp34-abi3-manylinux_2_17_armv7l
  cp34-abi3-manylinux2014_armv7l
  cp34-abi3-linux_armv7l
  cp33-abi3-manylinux_2_35_armv7l
  cp33-abi3-manylinux_2_34_armv7l
  cp33-abi3-manylinux_2_33_armv7l
  cp33-abi3-manylinux_2_32_armv7l
  cp33-abi3-manylinux_2_31_armv7l
  cp33-abi3-manylinux_2_30_armv7l
  cp33-abi3-manylinux_2_29_armv7l
  cp33-abi3-manylinux_2_28_armv7l
  cp33-abi3-manylinux_2_27_armv7l
  cp33-abi3-manylinux_2_26_armv7l
  cp33-abi3-manylinux_2_25_armv7l
  cp33-abi3-manylinux_2_24_armv7l
  cp33-abi3-manylinux_2_23_armv7l
  cp33-abi3-manylinux_2_22_armv7l
  cp33-abi3-manylinux_2_21_armv7l
  cp33-abi3-manylinux_2_20_armv7l
  cp33-abi3-manylinux_2_19_armv7l
  cp33-abi3-manylinux_2_18_armv7l
  cp33-abi3-manylinux_2_17_armv7l
  cp33-abi3-manylinux2014_armv7l
  cp33-abi3-linux_armv7l
  cp32-abi3-manylinux_2_35_armv7l
  cp32-abi3-manylinux_2_34_armv7l
  cp32-abi3-manylinux_2_33_armv7l
  cp32-abi3-manylinux_2_32_armv7l
  cp32-abi3-manylinux_2_31_armv7l
  cp32-abi3-manylinux_2_30_armv7l
  cp32-abi3-manylinux_2_29_armv7l
  cp32-abi3-manylinux_2_28_armv7l
  cp32-abi3-manylinux_2_27_armv7l
  cp32-abi3-manylinux_2_26_armv7l
  cp32-abi3-manylinux_2_25_armv7l
  cp32-abi3-manylinux_2_24_armv7l
  cp32-abi3-manylinux_2_23_armv7l
  cp32-abi3-manylinux_2_22_armv7l
  cp32-abi3-manylinux_2_21_armv7l
  cp32-abi3-manylinux_2_20_armv7l
  cp32-abi3-manylinux_2_19_armv7l
  cp32-abi3-manylinux_2_18_armv7l
  cp32-abi3-manylinux_2_17_armv7l
  cp32-abi3-manylinux2014_armv7l
  cp32-abi3-linux_armv7l
  py310-none-manylinux_2_35_armv7l
  py310-none-manylinux_2_34_armv7l
  py310-none-manylinux_2_33_armv7l
  py310-none-manylinux_2_32_armv7l
  py310-none-manylinux_2_31_armv7l
  py310-none-manylinux_2_30_armv7l
  py310-none-manylinux_2_29_armv7l
  py310-none-manylinux_2_28_armv7l
  py310-none-manylinux_2_27_armv7l
  py310-none-manylinux_2_26_armv7l
  py310-none-manylinux_2_25_armv7l
  py310-none-manylinux_2_24_armv7l
  py310-none-manylinux_2_23_armv7l
  py310-none-manylinux_2_22_armv7l
  py310-none-manylinux_2_21_armv7l
  py310-none-manylinux_2_20_armv7l
  py310-none-manylinux_2_19_armv7l
  py310-none-manylinux_2_18_armv7l
  py310-none-manylinux_2_17_armv7l
  py310-none-manylinux2014_armv7l
  py310-none-linux_armv7l
  py3-none-manylinux_2_35_armv7l
  py3-none-manylinux_2_34_armv7l
  py3-none-manylinux_2_33_armv7l
  py3-none-manylinux_2_32_armv7l
  py3-none-manylinux_2_31_armv7l
  py3-none-manylinux_2_30_armv7l
  py3-none-manylinux_2_29_armv7l
  py3-none-manylinux_2_28_armv7l
  py3-none-manylinux_2_27_armv7l
  py3-none-manylinux_2_26_armv7l
  py3-none-manylinux_2_25_armv7l
  py3-none-manylinux_2_24_armv7l
  py3-none-manylinux_2_23_armv7l
  py3-none-manylinux_2_22_armv7l
  py3-none-manylinux_2_21_armv7l
  py3-none-manylinux_2_20_armv7l
  py3-none-manylinux_2_19_armv7l
  py3-none-manylinux_2_18_armv7l
  py3-none-manylinux_2_17_armv7l
  py3-none-manylinux2014_armv7l
  py3-none-linux_armv7l
  py39-none-manylinux_2_35_armv7l
  py39-none-manylinux_2_34_armv7l
  py39-none-manylinux_2_33_armv7l
  py39-none-manylinux_2_32_armv7l
  py39-none-manylinux_2_31_armv7l
  py39-none-manylinux_2_30_armv7l
  py39-none-manylinux_2_29_armv7l
  py39-none-manylinux_2_28_armv7l
  py39-none-manylinux_2_27_armv7l
  py39-none-manylinux_2_26_armv7l
  py39-none-manylinux_2_25_armv7l
  py39-none-manylinux_2_24_armv7l
  py39-none-manylinux_2_23_armv7l
  py39-none-manylinux_2_22_armv7l
  py39-none-manylinux_2_21_armv7l
  py39-none-manylinux_2_20_armv7l
  py39-none-manylinux_2_19_armv7l
  py39-none-manylinux_2_18_armv7l
  py39-none-manylinux_2_17_armv7l
  py39-none-manylinux2014_armv7l
  py39-none-linux_armv7l
  py38-none-manylinux_2_35_armv7l
  py38-none-manylinux_2_34_armv7l
  py38-none-manylinux_2_33_armv7l
  py38-none-manylinux_2_32_armv7l
  py38-none-manylinux_2_31_armv7l
  py38-none-manylinux_2_30_armv7l
  py38-none-manylinux_2_29_armv7l
  py38-none-manylinux_2_28_armv7l
  py38-none-manylinux_2_27_armv7l
  py38-none-manylinux_2_26_armv7l
  py38-none-manylinux_2_25_armv7l
  py38-none-manylinux_2_24_armv7l
  py38-none-manylinux_2_23_armv7l
  py38-none-manylinux_2_22_armv7l
  py38-none-manylinux_2_21_armv7l
  py38-none-manylinux_2_20_armv7l
  py38-none-manylinux_2_19_armv7l
  py38-none-manylinux_2_18_armv7l
  py38-none-manylinux_2_17_armv7l
  py38-none-manylinux2014_armv7l
  py38-none-linux_armv7l
  py37-none-manylinux_2_35_armv7l
  py37-none-manylinux_2_34_armv7l
  py37-none-manylinux_2_33_armv7l
  py37-none-manylinux_2_32_armv7l
  py37-none-manylinux_2_31_armv7l
  py37-none-manylinux_2_30_armv7l
  py37-none-manylinux_2_29_armv7l
  py37-none-manylinux_2_28_armv7l
  py37-none-manylinux_2_27_armv7l
  py37-none-manylinux_2_26_armv7l
  py37-none-manylinux_2_25_armv7l
  py37-none-manylinux_2_24_armv7l
  py37-none-manylinux_2_23_armv7l
  py37-none-manylinux_2_22_armv7l
  py37-none-manylinux_2_21_armv7l
  py37-none-manylinux_2_20_armv7l
  py37-none-manylinux_2_19_armv7l
  py37-none-manylinux_2_18_armv7l
  py37-none-manylinux_2_17_armv7l
  py37-none-manylinux2014_armv7l
  py37-none-linux_armv7l
  py36-none-manylinux_2_35_armv7l
  py36-none-manylinux_2_34_armv7l
  py36-none-manylinux_2_33_armv7l
  py36-none-manylinux_2_32_armv7l
  py36-none-manylinux_2_31_armv7l
  py36-none-manylinux_2_30_armv7l
  py36-none-manylinux_2_29_armv7l
  py36-none-manylinux_2_28_armv7l
  py36-none-manylinux_2_27_armv7l
  py36-none-manylinux_2_26_armv7l
  py36-none-manylinux_2_25_armv7l
  py36-none-manylinux_2_24_armv7l
  py36-none-manylinux_2_23_armv7l
  py36-none-manylinux_2_22_armv7l
  py36-none-manylinux_2_21_armv7l
  py36-none-manylinux_2_20_armv7l
  py36-none-manylinux_2_19_armv7l
  py36-none-manylinux_2_18_armv7l
  py36-none-manylinux_2_17_armv7l
  py36-none-manylinux2014_armv7l
  py36-none-linux_armv7l
  py35-none-manylinux_2_35_armv7l
  py35-none-manylinux_2_34_armv7l
  py35-none-manylinux_2_33_armv7l
  py35-none-manylinux_2_32_armv7l
  py35-none-manylinux_2_31_armv7l
  py35-none-manylinux_2_30_armv7l
  py35-none-manylinux_2_29_armv7l
  py35-none-manylinux_2_28_armv7l
  py35-none-manylinux_2_27_armv7l
  py35-none-manylinux_2_26_armv7l
  py35-none-manylinux_2_25_armv7l
  py35-none-manylinux_2_24_armv7l
  py35-none-manylinux_2_23_armv7l
  py35-none-manylinux_2_22_armv7l
  py35-none-manylinux_2_21_armv7l
  py35-none-manylinux_2_20_armv7l
  py35-none-manylinux_2_19_armv7l
  py35-none-manylinux_2_18_armv7l
  py35-none-manylinux_2_17_armv7l
  py35-none-manylinux2014_armv7l
  py35-none-linux_armv7l
  py34-none-manylinux_2_35_armv7l
  py34-none-manylinux_2_34_armv7l
  py34-none-manylinux_2_33_armv7l
  py34-none-manylinux_2_32_armv7l
  py34-none-manylinux_2_31_armv7l
  py34-none-manylinux_2_30_armv7l
  py34-none-manylinux_2_29_armv7l
  py34-none-manylinux_2_28_armv7l
  py34-none-manylinux_2_27_armv7l
  py34-none-manylinux_2_26_armv7l
  py34-none-manylinux_2_25_armv7l
  py34-none-manylinux_2_24_armv7l
  py34-none-manylinux_2_23_armv7l
  py34-none-manylinux_2_22_armv7l
  py34-none-manylinux_2_21_armv7l
  py34-none-manylinux_2_20_armv7l
  py34-none-manylinux_2_19_armv7l
  py34-none-manylinux_2_18_armv7l
  py34-none-manylinux_2_17_armv7l
  py34-none-manylinux2014_armv7l
  py34-none-linux_armv7l
  py33-none-manylinux_2_35_armv7l
  py33-none-manylinux_2_34_armv7l
  py33-none-manylinux_2_33_armv7l
  py33-none-manylinux_2_32_armv7l
  py33-none-manylinux_2_31_armv7l
  py33-none-manylinux_2_30_armv7l
  py33-none-manylinux_2_29_armv7l
  py33-none-manylinux_2_28_armv7l
  py33-none-manylinux_2_27_armv7l
  py33-none-manylinux_2_26_armv7l
  py33-none-manylinux_2_25_armv7l
  py33-none-manylinux_2_24_armv7l
  py33-none-manylinux_2_23_armv7l
  py33-none-manylinux_2_22_armv7l
  py33-none-manylinux_2_21_armv7l
  py33-none-manylinux_2_20_armv7l
  py33-none-manylinux_2_19_armv7l
  py33-none-manylinux_2_18_armv7l
  py33-none-manylinux_2_17_armv7l
  py33-none-manylinux2014_armv7l
  py33-none-linux_armv7l
  py32-none-manylinux_2_35_armv7l
  py32-none-manylinux_2_34_armv7l
  py32-none-manylinux_2_33_armv7l
  py32-none-manylinux_2_32_armv7l
  py32-none-manylinux_2_31_armv7l
  py32-none-manylinux_2_30_armv7l
  py32-none-manylinux_2_29_armv7l
  py32-none-manylinux_2_28_armv7l
  py32-none-manylinux_2_27_armv7l
  py32-none-manylinux_2_26_armv7l
  py32-none-manylinux_2_25_armv7l
  py32-none-manylinux_2_24_armv7l
  py32-none-manylinux_2_23_armv7l
  py32-none-manylinux_2_22_armv7l
  py32-none-manylinux_2_21_armv7l
  py32-none-manylinux_2_20_armv7l
  py32-none-manylinux_2_19_armv7l
  py32-none-manylinux_2_18_armv7l
  py32-none-manylinux_2_17_armv7l
  py32-none-manylinux2014_armv7l
  py32-none-linux_armv7l
  py31-none-manylinux_2_35_armv7l
  py31-none-manylinux_2_34_armv7l
  py31-none-manylinux_2_33_armv7l
  py31-none-manylinux_2_32_armv7l
  py31-none-manylinux_2_31_armv7l
  py31-none-manylinux_2_30_armv7l
  py31-none-manylinux_2_29_armv7l
  py31-none-manylinux_2_28_armv7l
  py31-none-manylinux_2_27_armv7l
  py31-none-manylinux_2_26_armv7l
  py31-none-manylinux_2_25_armv7l
  py31-none-manylinux_2_24_armv7l
  py31-none-manylinux_2_23_armv7l
  py31-none-manylinux_2_22_armv7l
  py31-none-manylinux_2_21_armv7l
  py31-none-manylinux_2_20_armv7l
  py31-none-manylinux_2_19_armv7l
  py31-none-manylinux_2_18_armv7l
  py31-none-manylinux_2_17_armv7l
  py31-none-manylinux2014_armv7l
  py31-none-linux_armv7l
  py30-none-manylinux_2_35_armv7l
  py30-none-manylinux_2_34_armv7l
  py30-none-manylinux_2_33_armv7l
  py30-none-manylinux_2_32_armv7l
  py30-none-manylinux_2_31_armv7l
  py30-none-manylinux_2_30_armv7l
  py30-none-manylinux_2_29_armv7l
  py30-none-manylinux_2_28_armv7l
  py30-none-manylinux_2_27_armv7l
  py30-none-manylinux_2_26_armv7l
  py30-none-manylinux_2_25_armv7l
  py30-none-manylinux_2_24_armv7l
  py30-none-manylinux_2_23_armv7l
  py30-none-manylinux_2_22_armv7l
  py30-none-manylinux_2_21_armv7l
  py30-none-manylinux_2_20_armv7l
  py30-none-manylinux_2_19_armv7l
  py30-none-manylinux_2_18_armv7l
  py30-none-manylinux_2_17_armv7l
  py30-none-manylinux2014_armv7l
  py30-none-linux_armv7l
  cp310-none-any
  py310-none-any
  py3-none-any
  py39-none-any
  py38-none-any
  py37-none-any
  py36-none-any
  py35-none-any
  py34-none-any
  py33-none-any
  py32-none-any
  py31-none-any
  py30-none-any
root@onecloud ~#

**Comment by cibimo** [comment]
万分感谢
